baseURL = "https://www.example.com"
languageCode = "en-us"
title = "Mind Drip Media"
theme = "mdm"
removePathAccents = true



# HTML before the closing </head>
[params]
customHead = ""

# Navigation
[params.navigation]
logo = "images/logo.svg"
home = "Home"
about = "About"
content = "Content"
service = "Services"
contact = "Contact"

# Hero Area
[params.hero]
enable            = true
bg                = "images/logo.svg"
title             = ""
subtitle          = "Promoting Open Source through Media"
btnText           = ""

# counter
disableCountdown  = true
countdownYear = "2021"
countdownMonth = "12"
countdownDay  = "31"

# About Section
[params.about]
enable      = true
heading     = "Who we are"
description = "Mind Drip Media is the eventuality of many years of discussion by several Content Creators who love linux.  We look to become a resource for Linux and Open Source focused content and to encourage and help others get started in becoming an open source evangalist."

[[params.about.sliderItem]]
image   = "images/Point1.png"
[[params.about.sliderItem]]
image   = "images/Point2.png"
[[params.about.sliderItem]]
image   = "images/Point3.png"
[[params.about.sliderItem]]
image   = "images/Point4.png"


# Content Section
[params.content]
enable = true
title = "Our Shows"
[[params.content.contentItem]]
# use delay for reveal items one by one
image   = "images/ans.png"
link    = "http://www.asknoahshow.com"
title   = "Ask Noah Show"
description = "Noah's weekly Call-In Radio Show on KEQQ FM and streaming live at Asknoahshow.com"
delay   = "0s"

[[params.content.contentItem]]
image   = "images/tod.png"
link    = "https://www.theopiniondominion.org"
title   = "The Opinion Dominion"
description = "Two old Linux/Unix/OpenSource guys talking about the past and future, of *nix, Open Source and other Tech related things."
delay   = "0.2s"

[[params.content.contentItem]]
image   = "images/osv.png"
link    = "https://www.opensourcevoices.org"
title   = "The Opinion Dominion"
description = "A show focusing on the people involved in Open Source."
delay   = "0.4s"

[[params.content.contentItem]]
image   = "images/mdm.jpg"
link    = "https://www.youtube.com/minddripmedia"
title   = "Other Content"
description = "Check out our other youtube videos."
delay   = "0.6s"

# Service Section
[params.service]
enable      = false

# Call to Action Section
[params.cta]
enable      = true
bg          = "/images/image.png"
title       = "Get In Touch"
subtitle    = "Contact us through any of the contact pages for our shows."

[params.contact]
enable      = false
title       = "Get In Touch"
subtitle    = "Contact us through any of the contact pages for our shows."
